# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from container import service_pb2 as container_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in container/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContainerServiceStub(object):
    """`ContainerService` provides API to interact with `Container` smart contract
    in FS chain via other NeoFS nodes. All of those actions can be done
    equivalently by directly issuing transactions and RPC calls to FS chain
    nodes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/Put',
                request_serializer=container_dot_service__pb2.PutRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/Delete',
                request_serializer=container_dot_service__pb2.DeleteRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/Get',
                request_serializer=container_dot_service__pb2.GetRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.GetResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/List',
                request_serializer=container_dot_service__pb2.ListRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.ListResponse.FromString,
                _registered_method=True)
        self.SetExtendedACL = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/SetExtendedACL',
                request_serializer=container_dot_service__pb2.SetExtendedACLRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.SetExtendedACLResponse.FromString,
                _registered_method=True)
        self.GetExtendedACL = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/GetExtendedACL',
                request_serializer=container_dot_service__pb2.GetExtendedACLRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.GetExtendedACLResponse.FromString,
                _registered_method=True)
        self.AnnounceUsedSpace = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/AnnounceUsedSpace',
                request_serializer=container_dot_service__pb2.AnnounceUsedSpaceRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.AnnounceUsedSpaceResponse.FromString,
                _registered_method=True)
        self.SetAttribute = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/SetAttribute',
                request_serializer=container_dot_service__pb2.SetAttributeRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.SetAttributeResponse.FromString,
                _registered_method=True)
        self.RemoveAttribute = channel.unary_unary(
                '/neo.fs.v2.container.ContainerService/RemoveAttribute',
                request_serializer=container_dot_service__pb2.RemoveAttributeRequest.SerializeToString,
                response_deserializer=container_dot_service__pb2.RemoveAttributeResponse.FromString,
                _registered_method=True)


class ContainerServiceServicer(object):
    """`ContainerService` provides API to interact with `Container` smart contract
    in FS chain via other NeoFS nodes. All of those actions can be done
    equivalently by directly issuing transactions and RPC calls to FS chain
    nodes.
    """

    def Put(self, request, context):
        """Sends transaction calling contract method to create container, and waits
        for the transaction to be executed. Deadline is determined by the
        transport protocol (e.g. `grpc-timeout` header). If the deadline is not
        set, server waits 15s after submitting the transaction.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        container successfully created;
        - Common failures (SECTION_FAILURE_COMMON);
        - **CONTAINER_AWAIT_TIMEOUT** (3075, SECTION_CONTAINER): \
        transaction was sent but not executed within the deadline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Sends transaction calling contract method to delete container, and waits
        for the transaction to be executed. Deadline is determined by the
        transport protocol (e.g. `grpc-timeout` header). If the deadline is not
        set, server waits 15s after submitting the transaction.
        NOTE: a container deletion leads to the removal of every object in that
        container, regardless of any restrictions on the object removal (e.g. lock/locked
        object would be also removed).

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        container successfully removed;
        - Common failures (SECTION_FAILURE_COMMON);
        - **CONTAINER_LOCKED** (3074, SECTION_CONTAINER): \
        deleting a locked container is prohibited;
        - **CONTAINER_AWAIT_TIMEOUT** (3075, SECTION_CONTAINER): \
        transaction was sent but not executed within the deadline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Returns container structure from `Container` smart contract storage.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        container has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON);
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        requested container not found.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Returns all owner's containers from 'Container` smart contract' storage.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        container list has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExtendedACL(self, request, context):
        """Sends transaction calling contract method to set container's extended ACL,
        and waits for the transaction to be executed. Deadline is determined by
        the transport protocol (e.g. `grpc-timeout` header). If the deadline is
        not set, server waits 15s after submitting the transaction.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        container eACL successfully set;
        - Common failures (SECTION_FAILURE_COMMON);
        - **CONTAINER_AWAIT_TIMEOUT** (3075, SECTION_CONTAINER): \
        transaction was sent but not executed within the deadline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExtendedACL(self, request, context):
        """Returns Extended ACL table and signature from `Container` smart contract
        storage.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        container eACL has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON);
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        container not found;
        - **EACL_NOT_FOUND** (3073, SECTION_CONTAINER): \
        eACL table not found.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceUsedSpace(self, request, context):
        """Announces the space values used by the container for P2P synchronization.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        estimation of used space has been successfully announced;
        - Common failures (SECTION_FAILURE_COMMON).

        DEPRECATED: every storage node must send storage load directly to `container`
        contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttribute(self, request, context):
        """Sends transaction calling contract method to set container attribute, and
        waits for the transaction to be executed. Deadline is determined by the
        transport protocol (e.g. `grpc-timeout` header). If the deadline is not
        set, server waits 15s after submitting the transaction.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        attribute successfully set;
        - Common failures (SECTION_FAILURE_COMMON);
        - **CONTAINER_AWAIT_TIMEOUT** (3075, SECTION_CONTAINER): \
        transaction was sent but not executed within the deadline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAttribute(self, request, context):
        """Sends transaction calling contract method to remove container attribute,
        and waits for the transaction to be executed. Deadline is determined by
        the transport protocol (e.g. `grpc-timeout` header). If the deadline is
        not set, server waits 15s after submitting the transaction.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        attribute successfully removed;
        - Common failures (SECTION_FAILURE_COMMON);
        - **CONTAINER_AWAIT_TIMEOUT** (3075, SECTION_CONTAINER): \
        transaction was sent but not executed within the deadline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=container_dot_service__pb2.PutRequest.FromString,
                    response_serializer=container_dot_service__pb2.PutResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=container_dot_service__pb2.DeleteRequest.FromString,
                    response_serializer=container_dot_service__pb2.DeleteResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=container_dot_service__pb2.GetRequest.FromString,
                    response_serializer=container_dot_service__pb2.GetResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=container_dot_service__pb2.ListRequest.FromString,
                    response_serializer=container_dot_service__pb2.ListResponse.SerializeToString,
            ),
            'SetExtendedACL': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExtendedACL,
                    request_deserializer=container_dot_service__pb2.SetExtendedACLRequest.FromString,
                    response_serializer=container_dot_service__pb2.SetExtendedACLResponse.SerializeToString,
            ),
            'GetExtendedACL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExtendedACL,
                    request_deserializer=container_dot_service__pb2.GetExtendedACLRequest.FromString,
                    response_serializer=container_dot_service__pb2.GetExtendedACLResponse.SerializeToString,
            ),
            'AnnounceUsedSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceUsedSpace,
                    request_deserializer=container_dot_service__pb2.AnnounceUsedSpaceRequest.FromString,
                    response_serializer=container_dot_service__pb2.AnnounceUsedSpaceResponse.SerializeToString,
            ),
            'SetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttribute,
                    request_deserializer=container_dot_service__pb2.SetAttributeRequest.FromString,
                    response_serializer=container_dot_service__pb2.SetAttributeResponse.SerializeToString,
            ),
            'RemoveAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAttribute,
                    request_deserializer=container_dot_service__pb2.RemoveAttributeRequest.FromString,
                    response_serializer=container_dot_service__pb2.RemoveAttributeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neo.fs.v2.container.ContainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neo.fs.v2.container.ContainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContainerService(object):
    """`ContainerService` provides API to interact with `Container` smart contract
    in FS chain via other NeoFS nodes. All of those actions can be done
    equivalently by directly issuing transactions and RPC calls to FS chain
    nodes.
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/Put',
            container_dot_service__pb2.PutRequest.SerializeToString,
            container_dot_service__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/Delete',
            container_dot_service__pb2.DeleteRequest.SerializeToString,
            container_dot_service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/Get',
            container_dot_service__pb2.GetRequest.SerializeToString,
            container_dot_service__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/List',
            container_dot_service__pb2.ListRequest.SerializeToString,
            container_dot_service__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetExtendedACL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/SetExtendedACL',
            container_dot_service__pb2.SetExtendedACLRequest.SerializeToString,
            container_dot_service__pb2.SetExtendedACLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExtendedACL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/GetExtendedACL',
            container_dot_service__pb2.GetExtendedACLRequest.SerializeToString,
            container_dot_service__pb2.GetExtendedACLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceUsedSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/AnnounceUsedSpace',
            container_dot_service__pb2.AnnounceUsedSpaceRequest.SerializeToString,
            container_dot_service__pb2.AnnounceUsedSpaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/SetAttribute',
            container_dot_service__pb2.SetAttributeRequest.SerializeToString,
            container_dot_service__pb2.SetAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.container.ContainerService/RemoveAttribute',
            container_dot_service__pb2.RemoveAttributeRequest.SerializeToString,
            container_dot_service__pb2.RemoveAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
