# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from neofs.api.netmap import service_pb2 as netmap_dot_service__pb2


class NetmapServiceStub(object):
    """`NetmapService` provides methods to work with `Network Map` and the information
    required to build it. The resulting `Network Map` is stored in FS chain
    `Netmap` smart contract, while related information can be obtained from other
    NeoFS nodes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LocalNodeInfo = channel.unary_unary(
                '/neo.fs.v2.netmap.NetmapService/LocalNodeInfo',
                request_serializer=netmap_dot_service__pb2.LocalNodeInfoRequest.SerializeToString,
                response_deserializer=netmap_dot_service__pb2.LocalNodeInfoResponse.FromString,
                )
        self.NetworkInfo = channel.unary_unary(
                '/neo.fs.v2.netmap.NetmapService/NetworkInfo',
                request_serializer=netmap_dot_service__pb2.NetworkInfoRequest.SerializeToString,
                response_deserializer=netmap_dot_service__pb2.NetworkInfoResponse.FromString,
                )
        self.NetmapSnapshot = channel.unary_unary(
                '/neo.fs.v2.netmap.NetmapService/NetmapSnapshot',
                request_serializer=netmap_dot_service__pb2.NetmapSnapshotRequest.SerializeToString,
                response_deserializer=netmap_dot_service__pb2.NetmapSnapshotResponse.FromString,
                )


class NetmapServiceServicer(object):
    """`NetmapService` provides methods to work with `Network Map` and the information
    required to build it. The resulting `Network Map` is stored in FS chain
    `Netmap` smart contract, while related information can be obtained from other
    NeoFS nodes.
    """

    def LocalNodeInfo(self, request, context):
        """Get NodeInfo structure from the particular node directly.
        Node information can be taken from `Netmap` smart contract. In some cases, though,
        one may want to get recent information directly or to talk to the node not yet
        present in the `Network Map` to find out what API version can be used for
        further communication. This can be also used to check if a node is up and running.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        information about the server has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NetworkInfo(self, request, context):
        """Read recent information about the NeoFS network.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        information about the current network state has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NetmapSnapshot(self, request, context):
        """Returns network map snapshot of the current NeoFS epoch.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        information about the current network map has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetmapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LocalNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalNodeInfo,
                    request_deserializer=netmap_dot_service__pb2.LocalNodeInfoRequest.FromString,
                    response_serializer=netmap_dot_service__pb2.LocalNodeInfoResponse.SerializeToString,
            ),
            'NetworkInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.NetworkInfo,
                    request_deserializer=netmap_dot_service__pb2.NetworkInfoRequest.FromString,
                    response_serializer=netmap_dot_service__pb2.NetworkInfoResponse.SerializeToString,
            ),
            'NetmapSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.NetmapSnapshot,
                    request_deserializer=netmap_dot_service__pb2.NetmapSnapshotRequest.FromString,
                    response_serializer=netmap_dot_service__pb2.NetmapSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neo.fs.v2.netmap.NetmapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NetmapService(object):
    """`NetmapService` provides methods to work with `Network Map` and the information
    required to build it. The resulting `Network Map` is stored in FS chain
    `Netmap` smart contract, while related information can be obtained from other
    NeoFS nodes.
    """

    @staticmethod
    def LocalNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neo.fs.v2.netmap.NetmapService/LocalNodeInfo',
            netmap_dot_service__pb2.LocalNodeInfoRequest.SerializeToString,
            netmap_dot_service__pb2.LocalNodeInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NetworkInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neo.fs.v2.netmap.NetmapService/NetworkInfo',
            netmap_dot_service__pb2.NetworkInfoRequest.SerializeToString,
            netmap_dot_service__pb2.NetworkInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NetmapSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neo.fs.v2.netmap.NetmapService/NetmapSnapshot',
            netmap_dot_service__pb2.NetmapSnapshotRequest.SerializeToString,
            netmap_dot_service__pb2.NetmapSnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
