# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from reputation import service_pb2 as reputation_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reputation/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReputationServiceStub(object):
    """`ReputationService` provides mechanisms for exchanging trust values with
    other NeoFS nodes. Nodes rate each other's reputation based on how good they
    process requests and set a trust level based on that rating. The trust
    information is passed to the next nodes to check and aggregate unless the
    final result is recorded.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnnounceLocalTrust = channel.unary_unary(
                '/neo.fs.v2.reputation.ReputationService/AnnounceLocalTrust',
                request_serializer=reputation_dot_service__pb2.AnnounceLocalTrustRequest.SerializeToString,
                response_deserializer=reputation_dot_service__pb2.AnnounceLocalTrustResponse.FromString,
                _registered_method=True)
        self.AnnounceIntermediateResult = channel.unary_unary(
                '/neo.fs.v2.reputation.ReputationService/AnnounceIntermediateResult',
                request_serializer=reputation_dot_service__pb2.AnnounceIntermediateResultRequest.SerializeToString,
                response_deserializer=reputation_dot_service__pb2.AnnounceIntermediateResultResponse.FromString,
                _registered_method=True)


class ReputationServiceServicer(object):
    """`ReputationService` provides mechanisms for exchanging trust values with
    other NeoFS nodes. Nodes rate each other's reputation based on how good they
    process requests and set a trust level based on that rating. The trust
    information is passed to the next nodes to check and aggregate unless the
    final result is recorded.
    """

    def AnnounceLocalTrust(self, request, context):
        """Announce local client trust information to any node in NeoFS network.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        local trust has been successfully announced;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceIntermediateResult(self, request, context):
        """Announce the intermediate result of the iterative algorithm for
        calculating the global reputation of the node in NeoFS network.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        intermediate trust estimation has been successfully announced;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReputationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnnounceLocalTrust': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceLocalTrust,
                    request_deserializer=reputation_dot_service__pb2.AnnounceLocalTrustRequest.FromString,
                    response_serializer=reputation_dot_service__pb2.AnnounceLocalTrustResponse.SerializeToString,
            ),
            'AnnounceIntermediateResult': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceIntermediateResult,
                    request_deserializer=reputation_dot_service__pb2.AnnounceIntermediateResultRequest.FromString,
                    response_serializer=reputation_dot_service__pb2.AnnounceIntermediateResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neo.fs.v2.reputation.ReputationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neo.fs.v2.reputation.ReputationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReputationService(object):
    """`ReputationService` provides mechanisms for exchanging trust values with
    other NeoFS nodes. Nodes rate each other's reputation based on how good they
    process requests and set a trust level based on that rating. The trust
    information is passed to the next nodes to check and aggregate unless the
    final result is recorded.
    """

    @staticmethod
    def AnnounceLocalTrust(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.reputation.ReputationService/AnnounceLocalTrust',
            reputation_dot_service__pb2.AnnounceLocalTrustRequest.SerializeToString,
            reputation_dot_service__pb2.AnnounceLocalTrustResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceIntermediateResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.reputation.ReputationService/AnnounceIntermediateResult',
            reputation_dot_service__pb2.AnnounceIntermediateResultRequest.SerializeToString,
            reputation_dot_service__pb2.AnnounceIntermediateResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
