# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from neofs.api.reputation import service_pb2 as reputation_dot_service__pb2


class ReputationServiceStub(object):
    """`ReputationService` provides mechanisms for exchanging trust values with
    other NeoFS nodes. Nodes rate each other's reputation based on how good they
    process requests and set a trust level based on that rating. The trust
    information is passed to the next nodes to check and aggregate unless the
    final result is recorded.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnnounceLocalTrust = channel.unary_unary(
                '/neo.fs.v2.reputation.ReputationService/AnnounceLocalTrust',
                request_serializer=reputation_dot_service__pb2.AnnounceLocalTrustRequest.SerializeToString,
                response_deserializer=reputation_dot_service__pb2.AnnounceLocalTrustResponse.FromString,
                )
        self.AnnounceIntermediateResult = channel.unary_unary(
                '/neo.fs.v2.reputation.ReputationService/AnnounceIntermediateResult',
                request_serializer=reputation_dot_service__pb2.AnnounceIntermediateResultRequest.SerializeToString,
                response_deserializer=reputation_dot_service__pb2.AnnounceIntermediateResultResponse.FromString,
                )


class ReputationServiceServicer(object):
    """`ReputationService` provides mechanisms for exchanging trust values with
    other NeoFS nodes. Nodes rate each other's reputation based on how good they
    process requests and set a trust level based on that rating. The trust
    information is passed to the next nodes to check and aggregate unless the
    final result is recorded.
    """

    def AnnounceLocalTrust(self, request, context):
        """Announce local client trust information to any node in NeoFS network.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        local trust has been successfully announced;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceIntermediateResult(self, request, context):
        """Announce the intermediate result of the iterative algorithm for
        calculating the global reputation of the node in NeoFS network.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        intermediate trust estimation has been successfully announced;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReputationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnnounceLocalTrust': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceLocalTrust,
                    request_deserializer=reputation_dot_service__pb2.AnnounceLocalTrustRequest.FromString,
                    response_serializer=reputation_dot_service__pb2.AnnounceLocalTrustResponse.SerializeToString,
            ),
            'AnnounceIntermediateResult': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceIntermediateResult,
                    request_deserializer=reputation_dot_service__pb2.AnnounceIntermediateResultRequest.FromString,
                    response_serializer=reputation_dot_service__pb2.AnnounceIntermediateResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neo.fs.v2.reputation.ReputationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReputationService(object):
    """`ReputationService` provides mechanisms for exchanging trust values with
    other NeoFS nodes. Nodes rate each other's reputation based on how good they
    process requests and set a trust level based on that rating. The trust
    information is passed to the next nodes to check and aggregate unless the
    final result is recorded.
    """

    @staticmethod
    def AnnounceLocalTrust(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neo.fs.v2.reputation.ReputationService/AnnounceLocalTrust',
            reputation_dot_service__pb2.AnnounceLocalTrustRequest.SerializeToString,
            reputation_dot_service__pb2.AnnounceLocalTrustResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnnounceIntermediateResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neo.fs.v2.reputation.ReputationService/AnnounceIntermediateResult',
            reputation_dot_service__pb2.AnnounceIntermediateResultRequest.SerializeToString,
            reputation_dot_service__pb2.AnnounceIntermediateResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
