# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from object import service_pb2 as object_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in object/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectServiceStub(object):
    """`ObjectService` provides API for manipulating objects. Object operations do
    not affect FS chain and are only served by nodes in P2P style.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_stream(
                '/neo.fs.v2.object.ObjectService/Get',
                request_serializer=object_dot_service__pb2.GetRequest.SerializeToString,
                response_deserializer=object_dot_service__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Put = channel.stream_unary(
                '/neo.fs.v2.object.ObjectService/Put',
                request_serializer=object_dot_service__pb2.PutRequest.SerializeToString,
                response_deserializer=object_dot_service__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/neo.fs.v2.object.ObjectService/Delete',
                request_serializer=object_dot_service__pb2.DeleteRequest.SerializeToString,
                response_deserializer=object_dot_service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Head = channel.unary_unary(
                '/neo.fs.v2.object.ObjectService/Head',
                request_serializer=object_dot_service__pb2.HeadRequest.SerializeToString,
                response_deserializer=object_dot_service__pb2.HeadResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_stream(
                '/neo.fs.v2.object.ObjectService/Search',
                request_serializer=object_dot_service__pb2.SearchRequest.SerializeToString,
                response_deserializer=object_dot_service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.SearchV2 = channel.unary_unary(
                '/neo.fs.v2.object.ObjectService/SearchV2',
                request_serializer=object_dot_service__pb2.SearchV2Request.SerializeToString,
                response_deserializer=object_dot_service__pb2.SearchV2Response.FromString,
                _registered_method=True)
        self.GetRange = channel.unary_stream(
                '/neo.fs.v2.object.ObjectService/GetRange',
                request_serializer=object_dot_service__pb2.GetRangeRequest.SerializeToString,
                response_deserializer=object_dot_service__pb2.GetRangeResponse.FromString,
                _registered_method=True)
        self.GetRangeHash = channel.unary_unary(
                '/neo.fs.v2.object.ObjectService/GetRangeHash',
                request_serializer=object_dot_service__pb2.GetRangeHashRequest.SerializeToString,
                response_deserializer=object_dot_service__pb2.GetRangeHashResponse.FromString,
                _registered_method=True)
        self.Replicate = channel.unary_unary(
                '/neo.fs.v2.object.ObjectService/Replicate',
                request_serializer=object_dot_service__pb2.ReplicateRequest.SerializeToString,
                response_deserializer=object_dot_service__pb2.ReplicateResponse.FromString,
                _registered_method=True)


class ObjectServiceServicer(object):
    """`ObjectService` provides API for manipulating objects. Object operations do
    not affect FS chain and are only served by nodes in P2P style.
    """

    def Get(self, request, context):
        """Receive full object structure, including Headers and payload. Response uses
        gRPC stream. First response message carries the object with the requested address.
        Chunk messages are parts of the object's payload if it is needed. All
        messages, except the first one, carry payload chunks. The requested object can
        be restored by concatenation of object message payload and all chunks
        keeping the receiving order.

        Extended headers can change `Get` behaviour:
        * __NEOFS__NETMAP_EPOCH \
        Will use the requsted version of Network Map for object placement
        calculation. DEPRECATED: header ignored by servers.
        * __NEOFS__NETMAP_LOOKUP_DEPTH \
        Will try older versions (starting from `__NEOFS__NETMAP_EPOCH` if specified or
        the latest one otherwise) of Network Map to find an object until the depth
        limit is reached. DEPRECATED: header ignored by servers.

        Please refer to detailed `XHeader` description.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        object has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON);
        - **ACCESS_DENIED** (2048, SECTION_OBJECT): \
        read access to the object is denied;
        - **OBJECT_NOT_FOUND** (2049, SECTION_OBJECT): \
        object not found in container;
        - **OBJECT_ALREADY_REMOVED** (2052, SECTION_OBJECT): \
        the requested object has been marked as deleted;
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        object container not found;
        - **TOKEN_EXPIRED** (4097, SECTION_SESSION): \
        provided session token has expired.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request_iterator, context):
        """Put the object into container. Request uses gRPC stream. First message
        SHOULD be of PutHeader type. `ContainerID` and `OwnerID` of an object
        SHOULD be set. Session token SHOULD be obtained before `PUT` operation (see
        session package). Chunk messages are considered by server as a part of an
        object payload. All messages, except first one, SHOULD be payload chunks.
        Chunk messages SHOULD be sent in the direct order of fragmentation.

        Extended headers can change `Put` behaviour:
        * __NEOFS__NETMAP_EPOCH \
        Will use the requsted version of Network Map for object placement
        calculation. DEPRECATED: header ignored by servers.

        Please refer to detailed `XHeader` description.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        object has been successfully saved in the container;
        - **INCOMPLETE** (1, SECTION_SUCCESS): \
        object was put to some nodes, but the number of replicas is not sufficient
        to satisfy placement policy;
        - Common failures (SECTION_FAILURE_COMMON);
        - **ACCESS_DENIED** (2048, SECTION_OBJECT): \
        write access to the container is denied;
        - **LOCKED** (2050, SECTION_OBJECT): \
        placement of an object of type TOMBSTONE that includes at least one locked
        object is prohibited;
        - **LOCK_NON_REGULAR_OBJECT** (2051, SECTION_OBJECT): \
        placement of an object of type LOCK that includes at least one object of
        type other than REGULAR is prohibited;
        - **QUOTA_EXCEEDED** (2054, SECTION_OBJECT): \
        size quota set by user was exceeded;
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        object storage container not found;
        - **TOKEN_NOT_FOUND** (4096, SECTION_SESSION): \
        (for trusted object preparation) session private key does not exist or has
        been deleted;
        - **TOKEN_EXPIRED** (4097, SECTION_SESSION): \
        provided session token has expired.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete the object from a container. There is no immediate removal
        guarantee. Object will be marked for removal and deleted eventually.
        Notice that some types of objects (see ObjectType) can not be removed,
        currently it's Tombstone and Lock.

        Extended headers can change `Delete` behaviour:
        * __NEOFS__NETMAP_EPOCH \
        Will use the requsted version of Network Map for object placement
        calculation. DEPRECATED: header ignored by servers.

        Please refer to detailed `XHeader` description.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        object has been successfully marked to be removed from the container;
        - **INCOMPLETE** (1, SECTION_SUCCESS): \
        some nodes have accepted the deletion mark, but some may still store
        the object;
        - Common failures (SECTION_FAILURE_COMMON);
        - **ACCESS_DENIED** (2048, SECTION_OBJECT): \
        delete access to the object is denied;
        - **LOCKED** (2050, SECTION_OBJECT): \
        deleting a locked object is prohibited;
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        object container not found;
        - **TOKEN_EXPIRED** (4097, SECTION_SESSION): \
        provided session token has expired.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Head(self, request, context):
        """Returns the object Headers without data payload. By default full header is
        returned. If `main_only` request field is set, the short header with only
        the very minimal information will be returned instead.

        Extended headers can change `Head` behaviour:
        * __NEOFS__NETMAP_EPOCH \
        Will use the requsted version of Network Map for object placement
        calculation.

        Please refer to detailed `XHeader` description.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        object header has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON);
        - **ACCESS_DENIED** (2048, SECTION_OBJECT): \
        access to operation HEAD of the object is denied;
        - **OBJECT_NOT_FOUND** (2049, SECTION_OBJECT): \
        object not found in container;
        - **OBJECT_ALREADY_REMOVED** (2052, SECTION_OBJECT): \
        the requested object has been marked as deleted;
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        object container not found;
        - **TOKEN_EXPIRED** (4097, SECTION_SESSION): \
        provided session token has expired.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search objects in container. Search query allows to match by Object
        Header's filed values. Please see the corresponding NeoFS Technical
        Specification section for more details.

        DEPRECATED: please use SearchV2.

        Extended headers can change `Search` behaviour:
        * __NEOFS__NETMAP_EPOCH \
        Will use the requsted version of Network Map for object placement
        calculation.

        Please refer to detailed `XHeader` description.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        objects have been successfully selected;
        - **INCOMPLETE** (1, SECTION_SUCCESS): \
        some nodes were unable to process the request, so the result may
        not contain all data;
        - Common failures (SECTION_FAILURE_COMMON);
        - **ACCESS_DENIED** (2048, SECTION_OBJECT): \
        access to operation SEARCH of the object is denied;
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        search container not found;
        - **TOKEN_EXPIRED** (4097, SECTION_SESSION): \
        provided session token has expired.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchV2(self, request, context):
        """Search for objects in a container. Similar to Search, but:
        * sorted
        * limited in amount of returned data
        * single message
        * allows for additional header fields to be returned

        Result is ordered by the 1st requested attribute (if any) and object ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRange(self, request, context):
        """Get byte range of data payload. Range is set as an (offset, length) tuple.
        Like in `Get` method, the response uses gRPC stream. Requested range can be
        restored by concatenation of all received payload chunks keeping the receiving
        order.

        Extended headers can change `GetRange` behaviour:
        * __NEOFS__NETMAP_EPOCH \
        Will use the requsted version of Network Map for object placement
        calculation. DEPRECATED: header ignored by servers.
        * __NEOFS__NETMAP_LOOKUP_DEPTH \
        Will try older versions of Network Map to find an object until the depth
        limit is reached. DEPRECATED: header ignored by servers.

        Please refer to detailed `XHeader` description.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        data range of the object payload has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON);
        - **ACCESS_DENIED** (2048, SECTION_OBJECT): \
        access to operation RANGE of the object is denied;
        - **OBJECT_NOT_FOUND** (2049, SECTION_OBJECT): \
        object not found in container;
        - **OBJECT_ALREADY_REMOVED** (2052, SECTION_OBJECT): \
        the requested object has been marked as deleted.
        - **OUT_OF_RANGE** (2053, SECTION_OBJECT): \
        the requested range is out of bounds;
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        object container not found;
        - **TOKEN_EXPIRED** (4097, SECTION_SESSION): \
        provided session token has expired.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRangeHash(self, request, context):
        """Returns homomorphic or regular hash of object's payload range after
        applying XOR operation with the provided `salt`. Ranges are set of (offset,
        length) tuples. Hashes order in response corresponds to the ranges order in
        the request. Note that hash is calculated for XORed data.

        Extended headers can change `GetRangeHash` behaviour:
        * __NEOFS__NETMAP_EPOCH \
        Will use the requsted version of Network Map for object placement
        calculation. DEPRECATED: header ignored by servers.
        * __NEOFS__NETMAP_LOOKUP_DEPTH \
        Will try older versions of Network Map to find an object until the depth
        limit is reached. DEPRECATED: header ignored by servers.

        Please refer to detailed `XHeader` description.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        data range of the object payload has been successfully hashed;
        - Common failures (SECTION_FAILURE_COMMON);
        - **ACCESS_DENIED** (2048, SECTION_OBJECT): \
        access to operation RANGEHASH of the object is denied;
        - **OBJECT_NOT_FOUND** (2049, SECTION_OBJECT): \
        object not found in container;
        - **OUT_OF_RANGE** (2053, SECTION_OBJECT): \
        the requested range is out of bounds;
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        object container not found;
        - **TOKEN_EXPIRED** (4097, SECTION_SESSION): \
        provided session token has expired.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replicate(self, request, context):
        """Save replica of the object on the NeoFS storage node. Both client and
        server must authenticate NeoFS storage nodes matching storage policy of
        the container referenced by the replicated object. Thus, this operation is
        purely system: regular users should not pay attention to it but use Put.

        Statuses:
        - **OK** (0, SECTION_SUCCESS): \
        the object has been successfully replicated;
        - **INTERNAL_SERVER_ERROR** (1024, SECTION_FAILURE_COMMON): \
        internal server error described in the text message;
        - **ACCESS_DENIED** (2048, SECTION_OBJECT): \
        the client does not authenticate any NeoFS storage node matching storage
        policy of the container referenced by the replicated object
        - **CONTAINER_NOT_FOUND** (3072, SECTION_CONTAINER): \
        the container to which the replicated object is associated was not found.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_stream_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=object_dot_service__pb2.GetRequest.FromString,
                    response_serializer=object_dot_service__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.stream_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=object_dot_service__pb2.PutRequest.FromString,
                    response_serializer=object_dot_service__pb2.PutResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=object_dot_service__pb2.DeleteRequest.FromString,
                    response_serializer=object_dot_service__pb2.DeleteResponse.SerializeToString,
            ),
            'Head': grpc.unary_unary_rpc_method_handler(
                    servicer.Head,
                    request_deserializer=object_dot_service__pb2.HeadRequest.FromString,
                    response_serializer=object_dot_service__pb2.HeadResponse.SerializeToString,
            ),
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=object_dot_service__pb2.SearchRequest.FromString,
                    response_serializer=object_dot_service__pb2.SearchResponse.SerializeToString,
            ),
            'SearchV2': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchV2,
                    request_deserializer=object_dot_service__pb2.SearchV2Request.FromString,
                    response_serializer=object_dot_service__pb2.SearchV2Response.SerializeToString,
            ),
            'GetRange': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRange,
                    request_deserializer=object_dot_service__pb2.GetRangeRequest.FromString,
                    response_serializer=object_dot_service__pb2.GetRangeResponse.SerializeToString,
            ),
            'GetRangeHash': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRangeHash,
                    request_deserializer=object_dot_service__pb2.GetRangeHashRequest.FromString,
                    response_serializer=object_dot_service__pb2.GetRangeHashResponse.SerializeToString,
            ),
            'Replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=object_dot_service__pb2.ReplicateRequest.FromString,
                    response_serializer=object_dot_service__pb2.ReplicateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neo.fs.v2.object.ObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neo.fs.v2.object.ObjectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectService(object):
    """`ObjectService` provides API for manipulating objects. Object operations do
    not affect FS chain and are only served by nodes in P2P style.
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/neo.fs.v2.object.ObjectService/Get',
            object_dot_service__pb2.GetRequest.SerializeToString,
            object_dot_service__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/neo.fs.v2.object.ObjectService/Put',
            object_dot_service__pb2.PutRequest.SerializeToString,
            object_dot_service__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.object.ObjectService/Delete',
            object_dot_service__pb2.DeleteRequest.SerializeToString,
            object_dot_service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Head(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.object.ObjectService/Head',
            object_dot_service__pb2.HeadRequest.SerializeToString,
            object_dot_service__pb2.HeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/neo.fs.v2.object.ObjectService/Search',
            object_dot_service__pb2.SearchRequest.SerializeToString,
            object_dot_service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.object.ObjectService/SearchV2',
            object_dot_service__pb2.SearchV2Request.SerializeToString,
            object_dot_service__pb2.SearchV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/neo.fs.v2.object.ObjectService/GetRange',
            object_dot_service__pb2.GetRangeRequest.SerializeToString,
            object_dot_service__pb2.GetRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRangeHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.object.ObjectService/GetRangeHash',
            object_dot_service__pb2.GetRangeHashRequest.SerializeToString,
            object_dot_service__pb2.GetRangeHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.object.ObjectService/Replicate',
            object_dot_service__pb2.ReplicateRequest.SerializeToString,
            object_dot_service__pb2.ReplicateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
