# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from accounting import service_pb2 as accounting_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in accounting/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountingServiceStub(object):
    """Accounting service provides methods for interaction with FS chain via
    other NeoFS nodes to get information about the account balance. Deposit and
    Withdraw operations can't be implemented here, as they require Mainnet NeoFS
    smart contract invocation. Transfer operations between internal NeoFS
    accounts are possible if both use the same token type.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Balance = channel.unary_unary(
                '/neo.fs.v2.accounting.AccountingService/Balance',
                request_serializer=accounting_dot_service__pb2.BalanceRequest.SerializeToString,
                response_deserializer=accounting_dot_service__pb2.BalanceResponse.FromString,
                _registered_method=True)


class AccountingServiceServicer(object):
    """Accounting service provides methods for interaction with FS chain via
    other NeoFS nodes to get information about the account balance. Deposit and
    Withdraw operations can't be implemented here, as they require Mainnet NeoFS
    smart contract invocation. Transfer operations between internal NeoFS
    accounts are possible if both use the same token type.
    """

    def Balance(self, request, context):
        """Returns the amount of funds in GAS token for the requested NeoFS account.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        balance has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Balance': grpc.unary_unary_rpc_method_handler(
                    servicer.Balance,
                    request_deserializer=accounting_dot_service__pb2.BalanceRequest.FromString,
                    response_serializer=accounting_dot_service__pb2.BalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neo.fs.v2.accounting.AccountingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neo.fs.v2.accounting.AccountingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountingService(object):
    """Accounting service provides methods for interaction with FS chain via
    other NeoFS nodes to get information about the account balance. Deposit and
    Withdraw operations can't be implemented here, as they require Mainnet NeoFS
    smart contract invocation. Transfer operations between internal NeoFS
    accounts are possible if both use the same token type.
    """

    @staticmethod
    def Balance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.accounting.AccountingService/Balance',
            accounting_dot_service__pb2.BalanceRequest.SerializeToString,
            accounting_dot_service__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
