# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from neofs.api.accounting import service_pb2 as accounting_dot_service__pb2


class AccountingServiceStub(object):
    """Accounting service provides methods for interaction with FS chain via
    other NeoFS nodes to get information about the account balance. Deposit and
    Withdraw operations can't be implemented here, as they require Mainnet NeoFS
    smart contract invocation. Transfer operations between internal NeoFS
    accounts are possible if both use the same token type.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Balance = channel.unary_unary(
                '/neo.fs.v2.accounting.AccountingService/Balance',
                request_serializer=accounting_dot_service__pb2.BalanceRequest.SerializeToString,
                response_deserializer=accounting_dot_service__pb2.BalanceResponse.FromString,
                )


class AccountingServiceServicer(object):
    """Accounting service provides methods for interaction with FS chain via
    other NeoFS nodes to get information about the account balance. Deposit and
    Withdraw operations can't be implemented here, as they require Mainnet NeoFS
    smart contract invocation. Transfer operations between internal NeoFS
    accounts are possible if both use the same token type.
    """

    def Balance(self, request, context):
        """Returns the amount of funds in GAS token for the requested NeoFS account.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        balance has been successfully read;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Balance': grpc.unary_unary_rpc_method_handler(
                    servicer.Balance,
                    request_deserializer=accounting_dot_service__pb2.BalanceRequest.FromString,
                    response_serializer=accounting_dot_service__pb2.BalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neo.fs.v2.accounting.AccountingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountingService(object):
    """Accounting service provides methods for interaction with FS chain via
    other NeoFS nodes to get information about the account balance. Deposit and
    Withdraw operations can't be implemented here, as they require Mainnet NeoFS
    smart contract invocation. Transfer operations between internal NeoFS
    accounts are possible if both use the same token type.
    """

    @staticmethod
    def Balance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neo.fs.v2.accounting.AccountingService/Balance',
            accounting_dot_service__pb2.BalanceRequest.SerializeToString,
            accounting_dot_service__pb2.BalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
