# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from session import service_pb2 as session_dot_service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in session/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub(object):
    """`SessionService` allows to establish a temporary trust relationship between
    two peer nodes and generate a `SessionToken` as the proof of trust to be
    attached in requests for further verification. Please see corresponding
    section of NeoFS Technical Specification for details.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/neo.fs.v2.session.SessionService/Create',
                request_serializer=session_dot_service__pb2.CreateRequest.SerializeToString,
                response_deserializer=session_dot_service__pb2.CreateResponse.FromString,
                _registered_method=True)


class SessionServiceServicer(object):
    """`SessionService` allows to establish a temporary trust relationship between
    two peer nodes and generate a `SessionToken` as the proof of trust to be
    attached in requests for further verification. Please see corresponding
    section of NeoFS Technical Specification for details.
    """

    def Create(self, request, context):
        """Open a new session between two peers.

        Statuses:
        - **OK** (0, SECTION_SUCCESS):
        session has been successfully opened;
        - Common failures (SECTION_FAILURE_COMMON).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=session_dot_service__pb2.CreateRequest.FromString,
                    response_serializer=session_dot_service__pb2.CreateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neo.fs.v2.session.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neo.fs.v2.session.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """`SessionService` allows to establish a temporary trust relationship between
    two peer nodes and generate a `SessionToken` as the proof of trust to be
    attached in requests for further verification. Please see corresponding
    section of NeoFS Technical Specification for details.
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neo.fs.v2.session.SessionService/Create',
            session_dot_service__pb2.CreateRequest.SerializeToString,
            session_dot_service__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
